<a href="https://colab.research.google.com/github/QaziSaim/Python-Assignment/blob/main/1st_march_Numpy_assignment_ipynbst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code that provides functionalities to perform certain tasks without the need to write code from scratch. Python libraries contain modules, functions, and methods that developers can utilize to expedite development, enhance functionality, and solve specific problems efficiently.


What is the difference between Numpy array and List?

Numpy arrays are homogeneous collections of elements with fixed size and are more efficient in terms of memory and speed for numerical operations compared to Python lists, which are heterogeneous and can contain elements of different data types.


Find the shape, size, and dimension of the following array?

Shape: (3, 4)
Size: 12
Dimension: 2

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
first_row = arr[0]
print(first_row)


[1 2 3 4]


In [3]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
element = arr[2, 3]
print(element)


12


In [4]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
odd_elements = arr[::2, ::2]
print(odd_elements)


[[ 1  3]
 [ 9 11]]


In [5]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.83993153 0.6494302  0.91635661]
 [0.33381466 0.57824658 0.6375424 ]
 [0.59754877 0.92780451 0.03660068]]


In [6]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
new_arr = np.expand_dims(arr, axis=0)
print(new_arr.shape)

(1, 3, 4)


In [7]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
transposed_arr = np.transpose(arr)
print(transposed_arr)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [10]:
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# While multiplication
while_mul = A2 * B2

# Add both matrices
added_matrices = A2 + B2

# Subtract matrix B from matrix A
subtracted_matrix = A2 - B2

# Divide Matrix B by A
divided_matrix = B2 / A2